#!/usr/bin/env python3
"""
Experiment 14 — Research Synthesis & Reproducibility Audit
DC Motor Digital Twin & Control Lab

Purpose
-------
This experiment does NOT run a new Monte-Carlo simulation and does NOT retune
any controller. It audits and synthesizes the evidence already generated by
Experiments 08A–13.

The script:
1. Checks the expected experiment scripts/results.
2. Builds a machine-readable evidence-chain table.
3. Audits reproducibility metadata and known protocol requirements.
4. Cross-checks the headline robustness results from Experiments 10 and 13.
5. Produces a project manifest and publication/CV-oriented synthesis report.

Expected execution location
----------------------------
Run from the project root:

    python simulations/14_research_synthesis_audit.py

The script is intentionally conservative. Missing optional artifacts are
reported as WARN rather than fabricated or silently ignored.
"""

from __future__ import annotations

import csv
import hashlib
import re
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
SIM_DIR = PROJECT_ROOT / "simulations"
RESULTS_DIR = PROJECT_ROOT / "results"

REPORT_PATH = RESULTS_DIR / "14_research_synthesis_report.txt"
EVIDENCE_PATH = RESULTS_DIR / "14_evidence_matrix.csv"
AUDIT_PATH = RESULTS_DIR / "14_reproducibility_audit.csv"
AUDIT_TXT_PATH = RESULTS_DIR / "14_reproducibility_audit.txt"
CROSS_PATH = RESULTS_DIR / "14_cross_experiment_summary.csv"
MANIFEST_PATH = RESULTS_DIR / "14_project_manifest.csv"

SEED_EXP10 = 20260912
SEED_EXP13 = 20260913
UNCERTAINTY_PCT = 10.0

# Headline values recorded by Experiments 10 and 13.
EXP10 = {
    "RMS error": {"mean": 7.861, "median": 12.128, "win_pct": 82.0},
    "IAE": {"mean": 41.362, "median": 46.136, "win_pct": 96.0},
    "ISE": {"mean": 12.807, "median": 22.923, "win_pct": 82.0},
    "Overshoot": {"mean": 60.510, "median": 59.662, "win_pct": 100.0},
    "Settling": {"mean": 34.423, "median": 33.682, "win_pct": 98.9},
    "Saturation duration": {"mean": 51.143, "median": 51.258, "win_pct": 98.0},
    "RMS voltage": {"mean": 2.883, "median": 3.136, "win_pct": 98.0},
    "RMS current": {"mean": 1.224, "median": 1.505, "win_pct": 85.0},
    "Twin→true speed RMSE": {"mean": 58.085, "median": 62.347, "win_pct": 99.0},
}

EXP13 = {
    "RMS error": {"mean": 8.104, "median": 12.259, "win_pct": 81.8},
    "Overshoot": {"mean": 60.150, "median": 64.001, "win_pct": 100.0},
    "Settling": {"mean": 34.056, "median": 33.562, "win_pct": 98.9759},
    "Twin→true speed RMSE": {"mean": 58.006, "median": 61.639, "win_pct": 99.7003},
}

REQUIRED_FILES = [
    "simulations/10_uncertainty_robustness.py",
    "simulations/11_statistical_analysis.py",
    "simulations/12_uncertainty_interaction_analysis.py",
    "simulations/13_targeted_interaction_confirmation.py",
    "results/10_uncertainty_robustness_summary.csv",
    "results/11_*",
    "results/12_*",
    "results/13_targeted_interaction_summary.csv",
    "results/13_targeted_interaction_statistics.csv",
]

# Early experiments are audited by semantic filename discovery rather than
# assumed exact prefixes. This avoids false warnings when a repository uses
# names such as "08B_identified_model_validation.py".
EARLY_EXPERIMENT_HINTS = {
    "08A": ["08a", "baseline", "digital", "twin"],
    "08B": ["08b", "identified", "validation"],
    "09A": ["09a", "baseline", "control", "state"],
    "09B-v3": ["09b", "constraint", "control"],
}

EVIDENCE_ROWS = [
    {
        "experiment": "08A",
        "role": "Frozen digital twin",
        "evidence": "Identified DC motor parameter set frozen for downstream validation/control studies.",
        "new_simulations": "Yes",
        "status": "FOUND/VERIFY",
    },
    {
        "experiment": "08B",
        "role": "Model identification/validation",
        "evidence": "Established identified-model trajectory and validation evidence used by the later control experiments.",
        "new_simulations": "Yes",
        "status": "FOUND/VERIFY",
    },
    {
        "experiment": "09A",
        "role": "Baseline closed-loop control",
        "evidence": "Provides the baseline against which the constraint-aware controller is compared.",
        "new_simulations": "Yes",
        "status": "FOUND/VERIFY",
    },
    {
        "experiment": "09B-v3",
        "role": "Constraint-aware controller",
        "evidence": "Adds reference governance/constraint handling and supplies the frozen controller used in robustness studies.",
        "new_simulations": "Yes",
        "status": "FOUND/VERIFY",
    },
    {
        "experiment": "10",
        "role": "Uncertainty robustness",
        "evidence": "100 Monte-Carlo realizations with independent ±10% parameter uncertainty; no retuning/re-identification.",
        "new_simulations": "100",
        "status": "PASS",
    },
    {
        "experiment": "11",
        "role": "Statistical inference",
        "evidence": "Reanalysis of Experiment 10 using bootstrap CIs, Wilcoxon tests, Holm correction and rank-biserial effect sizes.",
        "new_simulations": "No",
        "status": "PASS",
    },
    {
        "experiment": "12",
        "role": "Interaction landscape",
        "evidence": "Second-order interaction analysis over the Experiment 10 uncertainty sample; bootstrap/permutation inference.",
        "new_simulations": "No",
        "status": "PASS",
    },
    {
        "experiment": "13",
        "role": "Targeted interaction confirmation",
        "evidence": "1,000 NEW Monte-Carlo realizations targeting R×Kt, R×b, Kt×b, Kt×Ke and Kt×J.",
        "new_simulations": "1,000",
        "status": "PASS",
    },
    {
        "experiment": "14",
        "role": "Research synthesis & reproducibility audit",
        "evidence": "Audits and integrates Experiments 08A–13 without new plant simulations or controller retuning.",
        "new_simulations": "No",
        "status": "CURRENT",
    },
]


@dataclass
class AuditRow:
    category: str
    check: str
    expected: str
    observed: str
    status: str
    note: str = ""


def ensure_results_dir() -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)


def resolve_patterns(patterns: Iterable[str]) -> list[tuple[str, list[Path]]]:
    resolved = []
    for pattern in patterns:
        if "*" in pattern or "?" in pattern or "[" in pattern:
            matches = sorted(PROJECT_ROOT.glob(pattern))
        else:
            p = PROJECT_ROOT / pattern
            matches = [p] if p.exists() else []
        resolved.append((pattern, matches))
    return resolved


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def audit_expected_files() -> list[AuditRow]:
    rows: list[AuditRow] = []

    # Audit the early experiment lineage without imposing a filename convention.
    all_py = sorted(SIM_DIR.glob("*.py"))
    for label, hints in EARLY_EXPERIMENT_HINTS.items():
        scored = []
        for path in all_py:
            name = path.name.lower()
            score = sum(1 for hint in hints if hint in name)
            if score:
                scored.append((score, path))

        scored.sort(key=lambda item: (-item[0], item[1].name))
        matches = [p for score, p in scored if score >= 2]

        if matches:
            names = "; ".join(str(p.relative_to(PROJECT_ROOT)) for p in matches[:5])
            rows.append(
                AuditRow(
                    "Artifacts",
                    f"Early experiment artifact discovery: {label}",
                    "A semantically matching source artifact",
                    names,
                    "PASS",
                    "Filename convention is not enforced.",
                )
            )
        else:
            rows.append(
                AuditRow(
                    "Artifacts",
                    f"Early experiment artifact discovery: {label}",
                    "A semantically matching source artifact",
                    "No confident semantic match",
                    "WARN",
                    "Review repository naming manually; this is an audit limitation, not proof of missing work.",
                )
            )

    for pattern, matches in resolve_patterns(REQUIRED_FILES):
        if matches:
            names = "; ".join(str(p.relative_to(PROJECT_ROOT)) for p in matches)
            rows.append(
                AuditRow(
                    "Artifacts",
                    f"Expected artifact: {pattern}",
                    "At least one match",
                    names,
                    "PASS",
                )
            )
        else:
            rows.append(
                AuditRow(
                    "Artifacts",
                    f"Expected artifact: {pattern}",
                    "At least one match",
                    "No match",
                    "WARN",
                    "Verify locally rather than assuming absence.",
                )
            )
    return rows


def audit_exp10_csv() -> list[AuditRow]:
    rows: list[AuditRow] = []
    path = RESULTS_DIR / "10_uncertainty_robustness_summary.csv"

    if not path.exists():
        return [
            AuditRow(
                "Experiment 10",
                "Summary CSV availability",
                "Present",
                "Missing",
                "WARN",
                "Experiment 10 headline values were recorded from the completed run, but local CSV verification is unavailable.",
            )
        ]

    try:
        df = pd.read_csv(path)
        rows.append(
            AuditRow(
                "Experiment 10",
                "Monte-Carlo row count",
                "100",
                str(len(df)),
                "PASS" if len(df) == 100 else "WARN",
            )
        )

        required = ["R", "L", "Kt", "Ke", "J", "b"]
        missing = [c for c in required if c not in df.columns]
        rows.append(
            AuditRow(
                "Experiment 10",
                "Uncertainty parameter columns",
                ", ".join(required),
                "All present" if not missing else f"Missing: {missing}",
                "PASS" if not missing else "WARN",
            )
        )

        for col in required:
            if col not in df.columns:
                continue
            if df[col].notna().all():
                rows.append(
                    AuditRow(
                        "Experiment 10",
                        f"No missing values in {col}",
                        "None",
                        "None",
                        "PASS",
                    )
                )
            else:
                rows.append(
                    AuditRow(
                        "Experiment 10",
                        f"No missing values in {col}",
                        "None",
                        str(int(df[col].isna().sum())),
                        "WARN",
                    )
                )

        # Settling time may legitimately contain missing values; they must remain NaN.
        settle_candidates = [
            c for c in df.columns
            if "settling" in c.lower() and "improvement" in c.lower()
        ]
        if settle_candidates:
            c = settle_candidates[0]
            nonnumeric = []
            for value in df[c].dropna():
                try:
                    float(value)
                except (TypeError, ValueError):
                    nonnumeric.append(str(value))
            rows.append(
                AuditRow(
                    "Experiment 10",
                    "Settling-time missing-value handling",
                    "Missing/unavailable values represented as NaN or equivalent, never as fabricated zero",
                    f"Column={c}; nonnumeric entries={len(nonnumeric)}",
                    "PASS" if not nonnumeric else "WARN",
                )
            )

    except Exception as exc:
        rows.append(
            AuditRow(
                "Experiment 10",
                "CSV readability",
                "Readable",
                repr(exc),
                "FAIL",
            )
        )
    return rows


def audit_source_metadata() -> list[AuditRow]:
    rows: list[AuditRow] = []

    source_checks = [
        (
            "10_uncertainty_robustness.py",
            [r"20260912", r"10\.0", r"±10", r"Monte-Carlo"],
        ),
        (
            "13_targeted_interaction_confirmation.py",
            [r"20260913", r"1000", r"±10"],
        ),
    ]

    for filename, patterns in source_checks:
        path = SIM_DIR / filename
        if not path.exists():
            rows.append(
                AuditRow(
                    "Source metadata",
                    filename,
                    "Present and contains protocol metadata",
                    "Missing",
                    "WARN",
                )
            )
            continue

        text = path.read_text(encoding="utf-8", errors="replace")
        missing = [p for p in patterns if not re.search(p, text, re.IGNORECASE)]
        rows.append(
            AuditRow(
                "Source metadata",
                f"Protocol markers in {filename}",
                "All expected markers found",
                "All found" if not missing else f"Missing patterns: {missing}",
                "PASS" if not missing else "WARN",
            )
        )

    return rows


def build_cross_experiment_table() -> pd.DataFrame:
    rows = []
    for metric, a in EXP10.items():
        b = EXP13.get(metric)
        rows.append(
            {
                "metric": metric,
                "exp10_mean_pct": a["mean"],
                "exp10_median_pct": a["median"],
                "exp10_win_pct": a["win_pct"],
                "exp13_mean_pct": np.nan if b is None else b["mean"],
                "exp13_median_pct": np.nan if b is None else b["median"],
                "exp13_win_pct": np.nan if b is None else b["win_pct"],
                "mean_difference_exp13_minus_exp10_pct": np.nan if b is None else b["mean"] - a["mean"],
                "median_difference_exp13_minus_exp10_pct": np.nan if b is None else b["median"] - a["median"],
                "win_difference_exp13_minus_exp10_pct_points": np.nan if b is None else b["win_pct"] - a["win_pct"],
            }
        )
    return pd.DataFrame(rows)


def create_manifest() -> pd.DataFrame:
    rows = []
    paths = [
        SIM_DIR,
        RESULTS_DIR,
    ]

    files = []
    for base in paths:
        if base.exists():
            files.extend(sorted(p for p in base.rglob("*") if p.is_file()))

    for path in files:
        stat = path.stat()
        rows.append(
            {
                "relative_path": str(path.relative_to(PROJECT_ROOT)),
                "size_bytes": stat.st_size,
                "sha256": sha256_file(path),
            }
        )

    return pd.DataFrame(rows)


def write_evidence_matrix() -> None:
    pd.DataFrame(EVIDENCE_ROWS).to_csv(EVIDENCE_PATH, index=False)


def write_audit(rows: list[AuditRow]) -> None:
    df = pd.DataFrame([asdict(r) for r in rows])
    df.to_csv(AUDIT_PATH, index=False)

    counts = df["status"].value_counts().to_dict() if not df.empty else {}
    lines = [
        "EXPERIMENT 14 — REPRODUCIBILITY AUDIT",
        "=" * 55,
        "",
        f"PASS: {counts.get('PASS', 0)}",
        f"WARN: {counts.get('WARN', 0)}",
        f"FAIL: {counts.get('FAIL', 0)}",
        "",
    ]

    for _, row in df.iterrows():
        lines.append(
            f"[{row['status']}] {row['category']} :: {row['check']}"
        )
        lines.append(f"  Expected: {row['expected']}")
        lines.append(f"  Observed: {row['observed']}")
        if row["note"]:
            lines.append(f"  Note: {row['note']}")
        lines.append("")

    AUDIT_TXT_PATH.write_text("\n".join(lines), encoding="utf-8")


def write_report(audit_rows: list[AuditRow], cross: pd.DataFrame) -> None:
    fail_count = sum(r.status == "FAIL" for r in audit_rows)
    warn_count = sum(r.status == "WARN" for r in audit_rows)

    report = []
    report += [
        "EXPERIMENT 14 — RESEARCH SYNTHESIS & REPRODUCIBILITY AUDIT",
        "DC MOTOR DIGITAL TWIN & CONTROL LAB",
        "=" * 72,
        "",
        "PURPOSE",
        "-------",
        "Experiment 14 consolidates the technical evidence generated by",
        "Experiments 08A–13. It does not run a new plant simulation, does not",
        "retune controller gains, and does not replace the statistical results",
        "already generated by Experiments 10–13.",
        "",
        "EVIDENCE CHAIN",
        "-------------",
        "08A  -> Frozen digital twin",
        "08B  -> Identification / validation",
        "09A  -> Baseline closed-loop controller",
        "09B-v3 -> Constraint-aware controller",
        "10   -> 100-realization ±10% Monte-Carlo robustness study",
        "11   -> Bootstrap / Wilcoxon / Holm statistical analysis",
        "12   -> Pairwise uncertainty-interaction landscape",
        "13   -> 1,000-new-realization targeted interaction confirmation",
        "14   -> Synthesis and reproducibility audit",
        "",
        "FROZEN DOWNSTREAM PROTOCOL",
        "---------------------------",
        "Identified twin parameters: R=2.011540, L=0.481997, Kt=0.105805,",
        "Ke=0.098059, J=0.021550, b=0.010715.",
        "Controller gain vector: [4.97875849, 6.45871589, -11.78057976].",
        "Reference = 30 rad/s; voltage limits = 0–12 V; load torque = 0.05.",
        "Monte-Carlo uncertainty = independent uniform ±10% on R, L, Kt, Ke, J, b.",
        "Experiment 10 seed = 20260912; Experiment 13 seed = 20260913.",
        "No re-identification or controller retuning was permitted in the robustness studies.",
        "",
        "ROBUSTNESS SYNTHESIS",
        "--------------------",
        "Experiment 10 evaluated 100 independent parameter realizations.",
        "Experiment 13 independently evaluated 1,000 new realizations.",
        "The targeted confirmation therefore increases the total number of",
        "unique Monte-Carlo plant realizations to 1,100 across the two robustness",
        "campaigns (Experiments 11 and 12 are reanalyses, not new plant samples).",
        "",
        "Headline Experiment 10 results:",
    ]

    for metric, vals in EXP10.items():
        report.append(
            f"  {metric}: mean={vals['mean']:.3f}%, "
            f"median={vals['median']:.3f}%, win={vals['win_pct']:.3f}%"
        )

    report += [
        "",
        "Targeted Experiment 13 results:",
    ]

    for metric, vals in EXP13.items():
        report.append(
            f"  {metric}: mean={vals['mean']:.3f}%, "
            f"median={vals['median']:.3f}%, win={vals['win_pct']:.3f}%"
        )

    report += [
        "",
        "INTERACTION CONFIRMATION",
        "-------------------------",
        "Experiment 13 confirmed statistically significant targeted interactions",
        "for RMS error: R×Kt, R×b, Kt×b, Kt×Ke, Kt×J.",
        "For settling time, all five targeted interactions survived Holm correction.",
        "For twin→true speed RMSE, R×Kt and Kt×J survived Holm correction.",
        "None of the five targeted interactions survived Holm correction for",
        "overshoot. This negative result is retained as part of the evidence.",
        "",
        "STATISTICAL INTERPRETATION",
        "--------------------------",
        "Experiment 11 found that the nine tested improvement metrics remained",
        "statistically significant after Holm correction in the 100-realization",
        "robustness sample. Effect sizes were also consistently positive for the",
        "constraint-aware strategy across the principal performance measures.",
        "",
        "Experiment 13 provides an independent 1,000-realization confirmation",
        "campaign. Its headline means, medians and win rates remain close to the",
        "Experiment 10 estimates for the metrics common to both experiments.",
        "This consistency is evidence of reproducibility under the specified",
        "uncertainty protocol; it is not a proof of universal superiority.",
        "",
        "IMPORTANT NEGATIVE / LIMITATION EVIDENCE",
        "-----------------------------------------",
        "Experiment 10 contains negative improvement realizations for some metrics,",
        "including RMS error, ISE and RMS current. Experiment 13 also contains",
        "negative RMS-error realizations. These tails demonstrate that the proposed",
        "controller is not uniformly better for every uncertain plant realization.",
        "The correct conclusion is therefore distributional/robustness-oriented,",
        "not universal.",
        "",
        "REPRODUCIBILITY STATUS",
        "----------------------",
        f"Audit FAIL count: {fail_count}",
        f"Audit WARN count: {warn_count}",
        "A WARN indicates that an artifact or local verification item could not",
        "be conclusively checked by this script. WARN is not treated as proof of",
        "failure. Review the generated audit CSV before publication.",
        "",
        "PUBLICATION-SAFE CLAIM",
        "----------------------",
        "Under the specified ±10% independent parameter-uncertainty domain, the",
        "constraint-aware digital-twin control strategy demonstrated robust",
        "performance advantages across the majority of Monte-Carlo realizations,",
        "with statistically significant aggregate effects and reproducible",
        "targeted interaction patterns. The study remains simulation-based and",
        "does not establish hardware performance or behavior outside the tested",
        "uncertainty domain.",
        "",
        "CV-SAFE PROJECT DESCRIPTION",
        "----------------------------",
        "Developed and statistically validated a constraint-aware DC-motor digital",
        "twin control framework combining system identification, integral",
        "state-feedback control, reference governance, Monte-Carlo uncertainty",
        "analysis and interaction-level sensitivity analysis across 1,100 unique",
        "plant realizations.",
        "",
        "RECOMMENDED NEXT STEP",
        "---------------------",
        "Freeze Experiments 08A–13 as the current evidence base. The next work",
        "should focus on packaging, documentation, figures, repository hygiene,",
        "and—when resources permit—independent hardware/HIL validation rather",
        "than adding another undirected Monte-Carlo campaign.",
        "",
        "CROSS-EXPERIMENT TABLE",
        "----------------------",
    ]

    for _, r in cross.iterrows():
        if pd.isna(r["exp13_mean_pct"]):
            continue
        report.append(
            f"  {r['metric']}: "
            f"Exp10 mean={r['exp10_mean_pct']:.3f}% -> "
            f"Exp13 mean={r['exp13_mean_pct']:.3f}%; "
            f"Δ={r['mean_difference_exp13_minus_exp10_pct']:.3f} percentage points"
        )

    REPORT_PATH.write_text("\n".join(report) + "\n", encoding="utf-8")


def main() -> None:
    ensure_results_dir()

    print("=" * 72)
    print("EXPERIMENT 14 — RESEARCH SYNTHESIS & REPRODUCIBILITY AUDIT")
    print("=" * 72)
    print("No new Monte-Carlo simulation. No controller retuning.")
    print()

    write_evidence_matrix()

    audit_rows = []
    audit_rows.extend(audit_expected_files())
    audit_rows.extend(audit_exp10_csv())
    audit_rows.extend(audit_source_metadata())

    cross = build_cross_experiment_table()
    cross.to_csv(CROSS_PATH, index=False)

    manifest = create_manifest()
    manifest.to_csv(MANIFEST_PATH, index=False)

    write_audit(audit_rows)
    write_report(audit_rows, cross)

    print(f"[OK] Evidence matrix: {EVIDENCE_PATH}")
    print(f"[OK] Reproducibility audit CSV: {AUDIT_PATH}")
    print(f"[OK] Reproducibility audit TXT: {AUDIT_TXT_PATH}")
    print(f"[OK] Cross-experiment summary: {CROSS_PATH}")
    print(f"[OK] Project manifest: {MANIFEST_PATH}")
    print(f"[OK] Synthesis report: {REPORT_PATH}")
    print()

    counts = pd.Series([r.status for r in audit_rows]).value_counts().to_dict()
    print("AUDIT COUNTS")
    print(f"  PASS: {counts.get('PASS', 0)}")
    print(f"  WARN: {counts.get('WARN', 0)}")
    print(f"  FAIL: {counts.get('FAIL', 0)}")
    print()

    if counts.get("FAIL", 0):
        print("STATUS: REVIEW REQUIRED — one or more hard checks failed.")
    elif counts.get("WARN", 0):
        print("STATUS: PASS WITH WARNINGS — review the audit before publication.")
    else:
        print("STATUS: PASS — synthesis and reproducibility audit completed.")
    print("=" * 72)


if __name__ == "__main__":
    main()
